#!/usr/bin/env bash
# Script that configures Nginx with a custom 404 page
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/server_name _;/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx start
